[hostname]
ssh_only = false
format = "[$hostname]($style) "
disabled = true

[hostname.aliases]
"ghar-server" = "ðŸ "
"Aarjavs-Macbook-Air" = "ðŸ’¼"

[directory]
style = "bright-blue"

[package]
format = '[$symbol$version]($style) '

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](purple)"

[git_branch]
format = "[$branch]($style)"
style = "yellow"

[git_status]
style = "#FFAFD7"

[aws]
disabled = false
symbol = "â˜ï¸"
style = "bold yellow"
format = "on [$symbol($profile)]($style) "

[custom.dotsync]
command = "cat /tmp/dot_status 2>/dev/null && rm /tmp/dot_status 2>/dev/null || echo ''"
when = "test -s /tmp/dot_status"
format = "[$output]($style) "
style = "bold green"

